name: Lifrea Heart Engine

on:
  schedule:
    - cron: "*/30 * * * *" # 30分ごと
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Call Lifrea Heart Script
        uses: actions/github-script@v6
        with:
          script: |
            const notion_token = process.env.NOTION_TOKEN;
            const notion_db = process.env.NOTION_DATABASE_ID;

            const fetch = (await import('node-fetch')).default;

            const now = new Date();
            const hour = now.getHours();
            const weekday = ["日","月","火","水","木","金","土"][now.getDay()];
            const weather = "晴れ";
            const temp = Math.floor(Math.random() * 10) + 20;
            const mood_seed = Math.floor(Math.random() * 100);

            const body = {
              parent: { database_id: notion_db },
              properties: {
                title: {
                  title: [{ text: { content: now.toISOString() } }]
                },
                time_iso: { date: { start: now.toISOString() }},
                hour: { number: hour },
                weekday: { select: { name: weekday }},
                weather: { select: { name: weather }},
                temp_c: { number: temp },
                mood_seed: { number: mood_seed }
              }
            };

            await fetch("https://api.notion.com/v1/pages", {
              method: "POST",
              headers: {
                "Authorization": `Bearer ${notion_token}`,
                "Content-Type": "application/json",
                "Notion-Version": "2022-06-28"
              },
              body: JSON.stringify(body)
            });
