name: Lifrea Heart Engine
on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Call Lifrea Heart Script
        uses: actions/github-script@v6
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        with:
          script: |
            const dbid  = process.env.NOTION_DATABASE_ID;
            const token = process.env.NOTION_TOKEN;

            // どのDBを見ているか確認
            const db = await fetch(`https://api.notion.com/v1/databases/${dbid}`, {
              headers: {
                "Authorization": `Bearer ${token}`,
                "Notion-Version": "2022-06-28"
              }
            }).then(r => r.json());
            console.log("DB properties:", Object.keys(db.properties || {})); // ここに ["数値","曜日","日付","天候","タイトル"] が出ればOK

            // JST 現在
            const now = new Date();
            const jst = new Date(now.getTime() + 9 * 60 * 60 * 1000);
            const weekdays = ["日","月","火","水","木","金","土"];

            // ★日本語5列DBに合わせたプロパティ名で送る★
            const body = {
              parent: { database_id: dbid },
              properties: {
                "タイトル": { "title": [ { "text": { "content": "Lifrea Heartbeat" } } ] },
                "日付":    { "date":  { "start": jst.toISOString() } },
                "曜日":    { "select": { "name": weekdays[jst.getDay()] } },
                "天候":    { "select": { "name": "晴" } },
                "数値":    { "number": jst.getHours() }
              }
            };

            const res = await fetch("https://api.notion.com/v1/pages", {
              method: "POST",
              headers: {
                "Authorization": `Bearer ${token}`,
                "Notion-Version": "2022-06-28",
                "Content-Type": "application/json"
              },
              body: JSON.stringify(body)
            });

            const text = await res.text();
            console.log("Result:", text);
            if (!res.ok) throw new Error(`Notion API error: ${res.status} ${text}`);
