name: Lifrea Heart Engine
on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Call Lifrea Heart Script
        uses: actions/github-script@v6
        with:
          script: |
            const fetch = global.fetch || (await import('node-fetch')).default;

            const dbid = process.env.NOTION_DATABASE_ID;
            const token = process.env.NOTION_TOKEN;

            // Step 1: データベース情報を取得
            const db = await fetch(`https://api.notion.com/v1/databases/${dbid}`, {
              headers: {
                "Authorization": `Bearer ${token}`,
                "Notion-Version": "2022-06-28"
              }
            }).then(r => r.json());

            console.log("DB properties:", Object.keys(db.properties));

            // Step 2: 現在時刻データ生成
            const now = new Date();
            const jst = new Date(now.getTime() + 9 * 60 * 60 * 1000);
            const weekdays = ["日","月","火","水","木","金","土"];

            // Step 3: 新規ページ作成
            const body = {
              parent: { database_id: dbid },
              properties: {
                title: { title: [{ text: { content: "Lifrea Heartbeat" } }] },
                time_iso: { date: { start: jst.toISOString() } },
                hour: { number: jst.getHours() },
                weekday: { select: { name: weekdays[jst.getDay()] } },
                weather: { select: { name: "晴" } },
                temp_c: { number: 23 },
                mood_seed: { number: Math.floor(Math.random() * 100) }
              }
            };

            const res = await fetch("https://api.notion.com/v1/pages", {
              method: "POST",
              headers: {
                "Authorization": `Bearer ${token}`,
                "Notion-Version": "2022-06-28",
                "Content-Type": "application/json"
              },
              body: JSON.stringify(body)
            });

            const text = await res.text();
            console.log("Result:", text);

            if (!res.ok) throw new Error(`Notion API error: ${res.status} ${text}`);
