name: OWM key quick test
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check OPENWEATHER_API_KEY length
        uses: actions/github-script@v6
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        with:
          script: |
            const k = process.env.OPENWEATHER_API_KEY || '';
            console.log('Key exists:', !!k);
            console.log('Key length:', k.length);        // 32 が理想
            console.log('Hex-like:', /^[a-f0-9]{32}$/i.test(k));
      - name: Try OpenWeather fetch
        uses: actions/github-script@v6
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        with:
          script: |
            const key = process.env.OPENWEATHER_API_KEY;
            const url = `https://api.openweathermap.org/data/2.5/weather?q=Tokyo,JP&units=metric&appid=${key}`;
            const r = await fetch(url);
            console.log('HTTP status:', r.status);
            const j = await r.json().catch(()=> ({}));
            console.log('Body:', j);
            if (!r.ok) throw new Error(`OWM failed: ${r.status}`);
